os: Visual Studio 2015

platform:
  - x86

configuration: Release

clone_folder: c:\projects\libwebrtc

build:
  project: PACKAGE.vcxproj

before_build:
  - cd c:\projects\libwebrtc
  - git submodule update --init --recursive
  - cmake -G "Visual Studio 14 2015" -DCMAKE_INSTALL_PREFIX=c:\projects\libwebrtc -DNINJA_ARGS="-j 2" -DBUILD_TESTS=ON .

artifacts:
  - path: libwebrtc-0.0.1-rc.4-win-x86.zip

test: OFF
